name: "Publish"

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/setup-action@v2.0.1
        with:
          version: 6.23.6
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@vini-vici'

      - run: npm i -g pnpm
      - run: pnpm build
        name: Build Assets
      - run: pnpm publish
        name: Publish to Npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

