name: "Publish"

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@vini-vici'

      - name: Build & Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile
          pnpm build
          npm publish

