name: "Release and Publish"

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    # if: ${{ github.ref == 'refs/heads/mainline' && !startsWith(github.ref, 'ref/tags')}}
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6
      - name: Configure Committer
        run: |
          git config user.name "Release Bot"
          git config user.email "<>"
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'
          scope: '@vini-vici'
      - run: npm ci
      - run: npm run release
        name: Run Release Command
      - name: Push Tag back to repo
        uses: ad-m/github-push-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch: mainline
          tags: true
      # Github Actions does not run from refs that were pushed by other actions, as such,
      # the publish mechanism needs to go here as well.
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
