name: "Release"

on:
  workflow_dispatch:
    

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Committer
        run: |
          git config user.name "Release Bot"
          git config user.email "<>"
      - name: Bump Version
        uses: qzb/standard-version@v1